name = "latency-checks"
main = "dist/index.mjs"

workers_dev = false
account_id = "dc941e8156f4a1336ca08481cb6d4222"

usage_model = "bundled"

compatibility_date = "2022-08-02"
compatibility_flags = []

routes = [
	{ pattern = "latency.garretcharp.com", custom_domain = true }
]

r2_buckets = [
	# { binding = "BUCKET_AMS", bucket_name = "r2-status-ams" },
	# { binding = "BUCKET_ARN", bucket_name = "r2-status-arn" },
	# { binding = "BUCKET_ATL", bucket_name = "r2-status-atl" },
	# { binding = "BUCKET_CDG", bucket_name = "r2-status-cdg" },
	# { binding = "BUCKET_DEN", bucket_name = "r2-status-den" },
	{ binding = "BUCKET_DFW", bucket_name = "r2-status-dfw" },
	# { binding = "BUCKET_EWR", bucket_name = "r2-status-ewr" },
	# { binding = "BUCKET_FRA", bucket_name = "r2-status-fra" },
	# { binding = "BUCKET_HKG", bucket_name = "r2-status-hkg" },
	# { binding = "BUCKET_IAD", bucket_name = "r2-status-iad" },
	# { binding = "BUCKET_KIX", bucket_name = "r2-status-kix" },
	# { binding = "BUCKET_LAX", bucket_name = "r2-status-lax" },
	{ binding = "BUCKET_LHR", bucket_name = "r2-status-lhr" },
	# { binding = "BUCKET_MAD", bucket_name = "r2-status-mad" },
	# { binding = "BUCKET_MIA", bucket_name = "r2-status-mia" },
	# { binding = "BUCKET_MRS", bucket_name = "r2-status-mrs" },
	# { binding = "BUCKET_MXP", bucket_name = "r2-status-mxp" },
	# { binding = "BUCKET_NRT", bucket_name = "r2-status-nrt" },
	# { binding = "BUCKET_ORD", bucket_name = "r2-status-ord" },
	# { binding = "BUCKET_PRG", bucket_name = "r2-status-prg" },
	# { binding = "BUCKET_SEA", bucket_name = "r2-status-sea" },
	# { binding = "BUCKET_SIN", bucket_name = "r2-status-sin" },
	# { binding = "BUCKET_SJC", bucket_name = "r2-status-sjc" },
	# { binding = "BUCKET_TPE", bucket_name = "r2-status-tpe" },
	# { binding = "BUCKET_VIE", bucket_name = "r2-status-vie" }
]

[durable_objects]
bindings = [
	{ name = "OperationsManager", class_name = "OperationsManager" }
]

[[migrations]]
tag = "v1"
new_classes = ["AggregationJobs"]

[[migrations]]
tag = "v2"
deleted_classes = ["AggregationJobs"]

[[migrations]]
tag = "v3"
new_classes = ["OperationsManager"]

[[unsafe.bindings]]
type = "analytics_engine"
name = "LatencyAnalytics"

[[unsafe.bindings]]
type = "analytics_engine"
name = "ErrorAnalytics"

[build]
command = "npm run build"

[triggers]
crons = []
